name: dask-ml-3.11
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-glm
  - multipledispatch >=0.4.9
  - mypy
  # https://github.com/numba/numba/issues/8304
  # - numba  # not supported on 3.11
  - numpy
  - numpydoc
  - packaging
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.11.*
  - scikit-learn <=1.1.3
  - scipy
  # - sparse  # needs numba
  - toolz
