name: dask-ml-3.13
channels:
  - conda-forge
  - defaults
dependencies:
  - dask-glm
  - multipledispatch >=0.4.9
  - mypy
  # - numba  # Version with Python 3.13 not on conda-forge yet
  - numpy
  - numpydoc
  - packaging
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.13.*
  - scikit-learn >=1.6.1
  - scipy
  - sparse
  - toolz
  - pip
  - pip:
      - git+https://github.com/dask/dask
      # Switch to conda for `numba` once a version with Python 3.13 support is on conda-forge
      - numba >= 0.61.0
