name: dask-ml-test
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage
  - Cython
  - flake8
  - heapdict
  - multipledispatch
  - nbsphinx
  - numpy
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - python=3.6
  - sortedcontainers
  - scikit-learn
  - scipy
  - sphinx
  - tornado
  - toolz
  - zict
  - pip:
    - dask-glm
    - sphinx-rtd-theme
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - git+https://github.com/dask/dask-searchcv.git
