name: dask-ml-3.11
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-glm
  - multipledispatch >=0.4.9
  - mypy
  - numba
  - numpy
  - numpydoc
  - packaging
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.11.*
  - scikit-learn <=1.1.3
  - scipy
  - sparse
  - toolz
