name: dask-ml-test
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-glm
  - isort==4.3.21
  - multipledispatch >=0.4.9
  - mypy
  - numba
  - numpy
  - numpydoc
  - packaging
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.8.*
  - scikit-learn>=1.0.0
  - scipy
  - sparse
  - toolz