parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      linux37:
        envFile: 'ci/environment-3.7.yaml'
        SKLARN_DEV: "no"
      linux38:
        envFile: 'ci/environment-3.8.yaml'
        SKLARN_DEV: "no"
      earliest:
        envFile: 'ci/environment-3.6.yaml'
        SKLARN_DEV: "no"
      sklearnDev:
        envFile: 'ci/environment-3.7.yaml'
        SKLEARN_DEV: "yes"
        WRAPPERS: "no"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: "Add conda to PATH (posix)"

  - bash: |
     conda install -y pip
     conda update -y conda
    displayName: "update conda"

  - bash: conda env create --quiet --file=$(envFile) --name=dask-ml-test && conda list -n dask-ml-test
    displayName: "install"

  - bash: |
      conda install -y -q pytorch cpuonly -c pytorch -n dask-ml-test
      source activate dask-ml-test
      pip install skorch
    displayName: "install PyTorch"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - bash: |
      pip install tensorflow>=2.3.0 scikeras
    displayName: "install Tensorflow and SciKeras"
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: |
      source activate dask-ml-test
      conda uninstall -y --force scikit-learn
      pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn
    displayName: "Install scikit-learn dev."
    condition: eq(variables.SKLEARN_DEV, 'yes')

  - script: |
      source activate dask-ml-test
      pytest --cov=dask_ml --cov-report=xml tests
    displayName: 'Run Tests'

  - bash: ./ci/code_checks.sh
    displayName: "Lint"
