parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      linux:
        envFile: 'ci/environment-3.7.yaml'
        SKLARN_DEV: "no"
      earliest:
        envFile: 'ci/environment-3.6.yaml'
        SKLARN_DEV: "no"
      sklearnDev:
        envFile: 'ci/environment-3.7.yaml'
        SKLEARN_DEV: "yes"

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: "Add conda to PATH (posix)"

  - bash: |
     conda install -y pip
     conda update -y conda
    displayName: "update conda"

  - bash: conda env create --quiet --file=$(envFile) --name=dask-ml-test && conda list -n dask-ml-test
    displayName: "install"

  - script: |
      source activate dask-ml-test
      conda uninstall -y --force scikit-learn
      pip install --pre -f https://sklearn-nightly.scdn8.secure.raxcdn.com scikit-learn
    displayName: "Install scikit-learn dev."
    condition: eq(variables.SKLEARN_DEV, 'yes')

  - script: |
      source activate dask-ml-test
      pytest --cov=dask_ml --cov-report=xml tests
    displayName: 'Run Tests'

  - script: |
      set -e
      source activate dask-ml-test
      flake8
    displayName: "Lint - flake8"
    continueOnError: true

  - script: |
      set -e
      source activate dask-ml-test
      black --check .
    displayName: "Lint - black"
    continueOnError: true

  - script: |
      set -e
      source activate dask-ml-test
      isort --recursive --check-only .
    displayName: "Lint - isort"
    continueOnError: true

  - script: |
      set -e
      source activate dask-ml-test
      bash <(curl -s https://codecov.io/bash)
    displayName: "Lint - codecov"
    continueOnError: true
